const express = require('express')
const bodyParser = require('body-parser')

const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
require('../controllers/authController')(app)
require('../controllers/productsController')(app)
require('../controllers/custumerBillController')(app)
require('../controllers/viewCustumerController')(app)
app.listen(3000)
